### ISSUE TITLE
Navbar desaparece

### ISSUE THREAD

**Issue by gracibrea** [rafegal/aula_bootstrap#1]
Olá Rafael
Terminei a atividade da aula de Bootstrap, mas percebi que como na sua tela, o menu do navbar desaparece quando a tela fica menor que 900px de largura.
Tentei arrumar, mas não consegui.
Tem alguma dica?
![image](https://user-images.githubusercontent.com/88933480/142503603-299d5f97-e8ce-4c39-b01a-9505b72b4e87.png)

**Comment by rafaelduarte1991** [comment]
Olá Cláudia,

O problema esta na classe class="nav-collapse collapse". 
Ao remover isso você acaba com o problema.

**Comment by gracibrea** [comment]
Muito obrigada @rafaelduarte1991 .
Funcionou mesmo!!!
